[package]
name = "stock_alerts"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
csv = "1.3.0"
toml = "0.8.16"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.12.5"
dotenv = "0.15.0"
