[stocks]
IBM = "Ibm"
NVDA = "Nvidia"
ALCBX = "Cibox"
ALO = "Alstom"
AIR = "Airbus"

[AWS]
bucket_name = "my_bucket_for_test"

[stock_api]
use_mock_data = "${SA_STOCK_API_USE_MOCK_DATA}"
api_key = "${SA_STOCK_API_KEY}"
api_url = "${SA_STOCK_API_URL}"